[package]
name = "bitcoin-address-book"
version = "0.1.0"
edition = "2021"
rust-version = "1.84"

[lib]
name = "bitcoin_address_book"
path = "src/lib.rs"

[dependencies]
bitcoin = "0.32.7"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = "debuginfo"
